name: Build image and push it to Docker Hub
on: push

jobs:
  push-image:
    name: Search_similar_context_by_Opensearch_and_Langchian
    runs-on: ubuntu-latest

    steps:
    - name: Get contents of repository
    - uses: actions/checkout@v4

    - name: Log in DockerHub🔐
      uses: docker/login-action@v3
      with:
        username: ${{secrets.MY_DOCKER_HUB_USERNAME}}
        password: ${{secrets.MY_DOCKER_HUB_TOKEN_OF_SEARCH_SIMILAR_CONTEXT_BY_OPENSEARCH_AND_LANGCHIAN}}

    - name: Build and push to Docker Hub💽
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: hoshizora39/search_similar_context_by_opensearch_and_langchian1.0:latest
